apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: crud-app
spec:
  selector:
    app: rotc-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
