apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: crud-app
spec:
  selector:
    app: rotc-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
